<?php
    $deviceIcon = [
        "BUZZER"=>"/img/buzzer.png",
        "COOLER_KEY"=>"/img/air-cooler.png",
        "FLOWERPOT"=> "/img/moisture.png",
        "SENSOR"=> "/img/carbon-monoxide.png",
        "IR"=> "/img/infrared.png",
        "LOCK"=> "/img/lock.png",
        "MOTIONDETECTOR"=> "/img/pir.png",
        "POWER"=> "/img/power-meter.png",
        "SOCKET"=> "/img/socket.png",
        "THERMOSTAT"=> "/img/thermostat.png",
        "TOUCHKEY"=> "/img/light-bulb.png",
        "TOUCHKEY_2B"=> "/img/light-bulb.png",
        "TOUCHKEY_3B"=> "/img/light-bulb.png",
        "TOUCHKEY_4B"=> "/img/light-bulb.png",
        "TOUCHKEY_16B"=> "/img/light-bulb.png",
        "VALVE"=> "/img/valve.png",
        "HEIGHTDETECTOR"=> "/img/height.png",
        "WINDOW_DOORSENSOR"=> "/img/window.png",
        "CURTAIN"=> "/img/curtain.png",
        "DIMMER"=>"/img/dimmer.png",
    ];

    $devicePublicName = [
        "BUZZER"=>"آزیر هوشمند",
        "COOLER_KEY"=>"کلید کولر",
        "FLOWERPOT"=> "رطوبت خاک",
        "SENSOR"=> "سنسور دود و گاز",
        "IR"=> "مادون قرمز",
        "LOCK"=> "قفل درب",
        "MOTIONDETECTOR"=> "سنسور تشخیص حرکت",
        "POWER"=> "انرژی سنج",
        "SOCKET"=> "پریز هوشمند",
        "THERMOSTAT"=> "ترموستات هوشمند",
        "TOUCHKEY"=> "کلید تک پل",
        "TOUCHKEY_2B"=> "کلید دو پل",
        "TOUCHKEY_3B"=> "کلید سه پل",
        "TOUCHKEY_4B"=> "کلید چهار پل",
        "TOUCHKEY_16B"=> "کلید شانزده پل",
        "VALVE"=> "شیر برقی",
        "HEIGHTDETECTOR"=> "سنسور سنجش ارتفاع",
        "WINDOW_DOORSENSOR"=> "سنسور درب و پنجره",
        "CURTAIN"=> "پرده برقی هوشمند",
        "DIMMER"=>"دیمر هوشمند",
    ];
?>